import "server-only";

import { parseServerEnv } from "./schema";

export const serverEnv = parseServerEnv({
  APP_ENV: process.env.APP_ENV,
  NEXT_PUBLIC_APP_ENV: process.env.NEXT_PUBLIC_APP_ENV,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
  NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
  NEXT_PUBLIC_OBSERVABILITY_ENABLED:
    process.env.NEXT_PUBLIC_OBSERVABILITY_ENABLED,
  NEXT_PUBLIC_UMAMI_WEBSITE_ID: process.env.NEXT_PUBLIC_UMAMI_WEBSITE_ID,
  NEXT_PUBLIC_UMAMI_SCRIPT_URL: process.env.NEXT_PUBLIC_UMAMI_SCRIPT_URL,
  OBSERVABILITY_ENABLED: process.env.OBSERVABILITY_ENABLED,
  LOG_LEVEL: process.env.LOG_LEVEL,
  SENTRY_DSN: process.env.SENTRY_DSN,
  SENTRY_ORG: process.env.SENTRY_ORG,
  SENTRY_PROJECT: process.env.SENTRY_PROJECT,
  SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
  SENTRY_RELEASE: process.env.SENTRY_RELEASE,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  AI_TEXT_PROVIDER: process.env.AI_TEXT_PROVIDER,
  AI_TEXT_MODEL: process.env.AI_TEXT_MODEL,
  GROQ_API_KEY: process.env.GROQ_API_KEY,
  AI_TEXT_FALLBACK_PROVIDER: process.env.AI_TEXT_FALLBACK_PROVIDER,
  CLOUDFLARE_TEXT_MODEL: process.env.CLOUDFLARE_TEXT_MODEL,
  AI_IMAGE_PROVIDER: process.env.AI_IMAGE_PROVIDER,
  AI_IMAGE_MODEL: process.env.AI_IMAGE_MODEL,
  CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID,
  CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN,
});
